"Filed out from Dolphin Smalltalk"!

Object subclass: #CefMouseEvent
	instanceVariableNames: 'x y modifiers'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

CefMouseEvent guid: (GUID fromString: '{5e955b13-b4d9-4019-b13e-2a3c8afcd361}')!

CefMouseEvent comment: ''!

!CefMouseEvent categoriesForClass!Kernel-Objects! !

!CefMouseEvent methodsFor!

modifiers
	^modifiers!

modifiers: anObject
	modifiers := anObject!

x
	^x!

x: anObject
	x := anObject!

y
	^y!

y: anObject
	y := anObject! !

!CefMouseEvent categoriesForMethods!
modifiers!accessing!public! !
modifiers:!accessing!private! !
x!accessing!public! !
x:!accessing!private! !
y!accessing!public! !
y:!accessing!private! !
!

