"Filed out from Dolphin Smalltalk"!

Object subclass: #CefRectangle
	instanceVariableNames: 'x y width height'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

CefRectangle guid: (GUID fromString: '{2f5d56c6-65f7-416e-8ab4-9e335f9dcdb5}')!

CefRectangle comment: ''!

!CefRectangle categoriesForClass!Kernel-Objects! !

!CefRectangle methodsFor!

height
	^height!

height: anObject
	height := anObject!

width
	^width!

width: anObject
	width := anObject!

x
	^x!

x: anObject
	x := anObject!

y
	^y!

y: anObject
	y := anObject! !

!CefRectangle categoriesForMethods!
height!accessing!public! !
height:!accessing!private! !
width!accessing!public! !
width:!accessing!private! !
x!accessing!public! !
x:!accessing!private! !
y!accessing!public! !
y:!accessing!private! !
!

